export const API_ENDPOINTS = {
  LOGIN: '/auth/login',
  FORGOT_PASSWORD: '/auth/forgot-password',
  GET_GALLERY: '/clubshawayi/list/gallery-image',
  LIST_FRANCHISE: '/clubshawayi/list/franchise',
  RUNNING_FRANCHISE: '/clubshawayi/list/running-franchise',
  HERO_SECTION: '/clubshawayi/list/hero-section',
  ABOUT_US: '/clubshawayi/list/about-us',
  BENIFITS_LIST: '/clubshawayi/list/benifits',
  FRANCHISE_LOCATION: '/clubshawayi/list/franchise-location',
  SOCIAL_LINK: '/clubshawayi/list/social-media-link',
  REQUIRED_ITEMS: '/clubshawayi/list/required-items',
  STAFF_DETAILS: '/clubshawayi/list/staff-details',
  INVESTMENT_ESTIMATE: '/clubshawayi/list/investment-estimate',
};
